### ISSUE TITLE
local implementation very slow

### ISSUE THREAD

**Issue by francoisnicolas** [adaptech-cz/Tesseract4Android#52] opened 2022-10-19 08:42 UTC
Hello,
Thank you for the sample.
I have build the Tesseract project, and the sample

When I change the option (first) : 
    // Use library from JitPack for simplicity
    implementation 'cz.adaptech:tesseract4android:4.1.1'
    // Or use library compiled locally
    //implementation project(':tesseract4android')

by (second option)
    // Use library from JitPack for simplicity
    //implementation 'cz.adaptech:tesseract4android:4.1.1'
    // Or use library compiled locally
    implementation project(':tesseract4android')

and execute the sample
It takes 30 seconds to recognize the text, and only about 2 seconds with first option

with the same smartphone.

Sincerely,

**Comment by Robyer** [comment] 2022-10-19 17:09
It seems it builds debug version of the library, which causes it to be so slow. You can force release build by adding:
`arguments "-DCMAKE_BUILD_TYPE=Release"`
in the Tesseract4Android's build.gradle file in section `android { defaultConfig { externalNativeBuild { cmake { ... } } } }`

**Comment by francoisnicolas** [comment] 2022-10-20 06:56
It doesn't work.
I can't select openmp release version for sample.
So, I have compiled in release + openmp version in another project (that doesn't have sample).
I have created a folder libs in the project containing sample and put in it the aar
added :
flatDir {
dirs 'libs'
}
in project gradle

and :
implementation project (':tesseract4android')

I can compile standard release, but not openmp release, because I can't select  openmp version for sample, and the compiler doesn't want to link standard release (sample) with openmp release (tesseract project)
And now, It asks me to sign the release version. I added a signature, but dradle doesn't to compile !

You succeded to compile and publish the aar. Perhaps there ar options in your compiler environment that are not included in the files of the project you published on github.

I surely haven't enough knowledge to compile and get the aar (efficient version : openmp)

**Comment by francoisnicolas** [comment] 2022-10-20 08:15
Now, I have built a signed APK (with local build standard release aar), and it works (speed is good)
But, for development, it's a bit compilcated.
Look at the attached copy of screen for adding openmp for sample in order to link correctly, and how to configure for building in debug mode/release mode/release openmp mode with  aar locally compiled.
If sample in the project causes problems for building at the same time tesseract and the sample, you could add it in an other project and explain in the readme how to add aar (for linking) (it wiil be more simple for building an app and take less time to compile : we have to compile one time tesseract, but many times the project we are creating)

I don't understand why gradle can compile debug mode with the aar stored on jitpack, and the speed of OCR is good.

![gradle 1](https://user-images.githubusercontent.com/19637957/196893757-ae5da9d7-d148-45f5-aa41-577358b968f2.png)
![gradle 2](https://user-images.githubusercontent.com/19637957/196893760-16efc663-0281-41db-a2ad-5ec7ba937ecf.png)

**Comment by Robyer** [comment] 2022-10-20 23:33
@francoisnicolas I'll check this later. Just for you info, I was never using the local dependency on this library from app project (as it's commented out in the sample). I always first compiled the library to the local maven repository and then used it in app project again from the local maven repository.

**Comment by Robyer** [comment] 2022-10-21 14:51
@francoisnicolas TL;DR: Get latest commits and see updated sample code.

> I don't understand why gradle can compile debug mode with the aar stored on jitpack, and the speed of OCR is good.

It's because AAR artifacts are built from release build type (which is fast). As I said in my previous comment (https://github.com/adaptech-cz/Tesseract4Android/issues/52#issuecomment-1284325036), you can configure debug build to also compile release version of library and it works. I commited this change, so it will work that way by default (see https://github.com/adaptech-cz/Tesseract4Android/commit/5c069b26b2484b88a06480c6ad64be10bc425a96).

> I can compile standard release, but not openmp release, because I can't select openmp version for sample

You can't choose the standard/openmp flavor in the Android Studio, because the sample app doesn't provide same flavors. You can specify what flavor to build in the build.gradle file directly. I now changed the code to be more explicit, so you can see how to use openmp flavor easily. See this commit: https://github.com/adaptech-cz/Tesseract4Android/commit/d81bf53bb39dd87a966aa8035f90c532c9a1bc46

**Comment by Robyer** [comment] 2022-10-21 16:01
I'm also publishing version 4.1.1a, which will be available on JitPack both in standard and openmp variant. See readme for updated dependencies block. It may take some time before JitPack builds the new version, so meanwhile see the updated sample/docs for local build / using local maven repository.

**Comment by francoisnicolas** [comment] 2022-10-24 09:42
![tesseract compile4](https://user-images.githubusercontent.com/19637957/197497732-631116c5-9ede-4d55-b94e-1588dd8adfdd.png)
![tesseract compile2](https://user-images.githubusercontent.com/19637957/197497737-d76c6ac4-3d63-4ec7-a242-a394dfc5f8ca.png)
![tesseract compile1](https://user-images.githubusercontent.com/19637957/197497742-e3dd2574-6578-4041-a5b3-c78e1af3bb23.png)
![tesseract compile5](https://user-images.githubusercontent.com/19637957/197497746-84c4b8a9-13cb-428e-88ff-305ab6da352e.png)
![tesseract compile3](https://user-images.githubusercontent.com/19637957/197497749-8243ad50-1547-4dd5-8bdc-da55ee4698e8.png)

I succeded to compile the different versions debug, release, openmp debug and openmp release.
But, I failed to link with the aar locally, there was a compiler error.
I succeeded by copying the aar file to the libs folder and then adding a reference to the libs folder in the build.gradle

I have attached the screenshots of the different operations

Thanks again for your work

**Comment by Robyer** [comment] 2022-10-24 12:12
@francoisnicolas I don't understand why are you copying AAR files around at all. With current sample, you just uncomment the lines and change "standard" to "opencv" as you did and you are done.

And if you don't plan to change anything in the Tesseract4Android library, then it's even easier to just consume it directly from JitPack, where opencv variant is now correctly working.

**Comment by Robyer** [comment] 2022-10-24 12:14
@francoisnicolas I don't understand why are you copying AAR files around at all. With current sample, you just uncomment the lines and change "standard" to "openmp" as you did and you are done.

And if you don't plan to change anything in the Tesseract4Android library, then it's even easier to just consume it directly from JitPack, where openmp variant is now correctly working.

**Comment by francoisnicolas** [comment] 2022-10-24 12:53
ok, I will try later. It's the first I compile such complex project, and there are many options/configurations that I have never used.

**Comment by francoisnicolas** [comment] 2022-10-24 17:49
Now, it's ok.
This morning, I tried these options,  but I fail. But this evening, I succeed. (debug version)
For release version, Android studio ask me to  sign the App, I have provided a sign key (that I have for an other project, but it fail : perhaps I have to change the name of the project : com..... . .... ?)

I have found a site that perhaps will interest you : bytedeco.org  or https://github.com/bytedeco
You could ask to reference your project.

In the project, you could enable parallel build : in gradle.properties :   org.gradle.parallel=true
And if you want to save time, you can compile all the project in a RAMDISK (after having saved all the files of the project on an hard disk, with the help of 7zip for example)
If you use a windows PC : 
http://www.ltr-data.se/opencode.html/
http://www.ltr-data.se/files/imdiskinst.exe
and a toolkit : https://sourceforge.net/projects/imdisk-toolkit/
to launch the App : in configuration panel : type in search bar :   imdisk
with the toolkit, you can launch by icon


Here is a batch ms dos script, in order to create a 2go ramdisk  (letter G:)  (you can add it in startup folder of windows)


@echo off

:: BatchGotAdmin7
:: From http://stackoverflow.com/a/10052222/1460422
:-------------------------------------
REM  --> Check for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
echo Requesting administrative privileges...
goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
set params = %*:"=""
echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

"%temp%\getadmin.vbs"
del "%temp%\getadmin.vbs"
exit /B

:gotAdmin
pushd "%CD%"
CD /D "%~dp0"
:--------------------------------------
imdisk -a -s 2G -m G: -p "/fs:ntfs /q /y"

**Comment by Robyer** [comment] 2022-10-24 19:13
> Now, it's ok.
This morning, I tried these options, but I fail. But this evening, I succeed. (debug version)
For release version, Android studio ask me to sign the App, I have provided a sign key (that I have for an other project, but it fail : perhaps I have to change the name of the project : com..... . .... ?)

Can you tell me what exactly are you trying to achieve? How do you want to integrate this library in your project? Because it feels to me like you are doing something unnecessary complicated.

Normally when using this library, you would just add dependencies as stated in readme: https://github.com/adaptech-cz/Tesseract4Android#usage
Do you plan to do something more complex that just listing this dependency in your project is not enough?

**Comment by francoisnicolas** [comment] 2022-10-24 19:22
android studio, gradle, android always evolve and have new version. We have to always upgrade, so I prefer to have all the sources of the programs and be able to compile it (and not upgrade gralde,...)
This week-end, I upgrade android studio, and many program can't compile any more.
On windows, with visual studio, there are programs that I have written 20 years ago, and I can compile them and run. them
________________________________
De : Robert Pösel ***@***.***>
Envoyé : lundi 24 octobre 2022 21:13
À : adaptech-cz/Tesseract4Android ***@***.***>
Cc : francoisnicolas ***@***.***>; Mention ***@***.***>
Objet : Re: [adaptech-cz/Tesseract4Android] local implementation very slow (Issue #52)


Now, it's ok.
This morning, I tried these options, but I fail. But this evening, I succeed. (debug version)
For release version, Android studio ask me to sign the App, I have provided a sign key (that I have for an other project, but it fail : perhaps I have to change the name of the project : com..... . .... ?)

Can you tell me what exactly are you trying to achieve? How do you want to integrate this library in your project? Because it feels to me like you are doing something unnecessary complicated.

Normally when using this library, you would just add dependencies as stated in readme: https://github.com/adaptech-cz/Tesseract4Android#usage
Do you plan to do something more complex that just listing this dependency in your project is not enough?

**Comment by Robyer** [comment] 2022-10-24 21:33
I see. In that case your problem is not Gradle, but Android Studio. I would say Gradle is designed in a way to have reproducible builds even for older projects. You just have to build it manually, and not opening it in Android Studio (which always suggests or even requires updating the Gradle to new version, in order to work with the project).

For more info see this first section https://developer.android.com/studio/build/building-cmdline and then https://docs.gradle.org/current/userguide/gradle_wrapper.html for more context.

As I stated in readme, you can compile AAR manually by just calling `gradlew tesseract4android:assembleRelease` in the project folder, for example.

But your issue with other projects may be caused by something else, like not available dependencies. Especially because not a long time ago was shutdown JCenter repository. So... it's not enough to have source code of the library you want, but you also need to have all the dependencies... Maybe you would need to have own custom Maven repository mirror, where you would mirror all packages you need for all your libraries and projects. (But that's out of scope for this.)

Anyway, let me know if you need something else from me, or you have solved your issues now :-)

**Comment by francoisnicolas** [comment] 2022-10-25 05:34
Thank you for all.
For the moment, I continue to compile debug version the time I create the App. Later, I will build signed APK, and if there are problems, I will contact you again.

**Comment by francoisnicolas** [comment] 2022-10-25 05:36
You can remove all  these comments from github, as it will not interest anyone else.
It miss a mail between developpers on github

**Closed** 2022-10-25 08:30 UTC
